### ISSUE TITLE
WebApplication specific default

### ISSUE THREAD

**Issue by Tobias-08** [Yvand/SPBypassLoginPage#11]
Hi,
in our setup we have multiple SPTrustedIdentityTokenIssuers and different WebApplications should use a different SPTrustedIdentityTokenIssuer as default. Is this solution able (or could be extended) to support a WebApplication-specific configuration of the default? In my understanding at the moment only a SPFarm property is supported.

Thanks!
Tobias

**Comment by Yvand** [comment]
Hi @Tobias-08, you are correct, the settings for this page are global and not per web application.
It looks like code may check for web application-specific properties in SPWebApplication.Properties, before SPFarm.Properties.
If you decide to implement this, feel free to submit a PR to improve this project!

**Comment by Tobias-08** [comment]
Hi @Yvand,

thanks for your response. I misunderstood the default behavior: Redirecting to the first token issuer it finds in the current zone (!, not farm) is just fine. So my feature request is unnecessary.

Thanks!
Tobias
