### ISSUE TITLE
How does this affect search?

### ISSUE THREAD

**Issue by kayodebristol** [Yvand/SPBypassLoginPage#3]
Sorry to bother you. Looked through the code, but I couldn't see how the login page bypass would direct 'normal' users to the trusted provider while also sending the search crawler to Windows. That's scenario where most folks would want to use a bypass login page.  

Also, sorry in advance if I screw up labeling this correctly.

**Comment by Yvand** [comment]
The search crawler is not impacted at all by this custom page, it does not even reach it.
When it starts crawling a SharePoint site, mssdmn immediately initiates NTLM handshake and is not redirected as anonymous users are

**Comment by kayodebristol** [comment]
Wow! Thanks. You have no idea how many problems this will fix. Thanks Again.
