### ISSUE TITLE
API requests doesn't authenticate properly when IP bypass is configured

### ISSUE THREAD

**Issue by nicolas6969** [Yvand/SPBypassLoginPage#9]
Hey guys,
I really like your solution, it works reliable and stable for regular use cases. 

I'm currently faced with the following problem: When I call the SharePoint API, the authentication is not properly working.
I have a webapplication with OKTA and Windows authentication configured. The server IP calling the API has been set to windows auth via "CustomBypassLogin_WindowsAuthIPs". When calling the webapplication URL, I'm presented with the windows authentication popup as expected.

The problem is, when I call the API directly like
/_vti_bin/client.svc/SP.APIHubConnector.GetListItems(listName='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',queryOptions='top%202')

I'm faced with a "System.UnauthorizedAccessException" error without any possiblity of authentication. To confirm the OOTB behaviour, I tested the same on a webapp with Windows authentication only, and it worked properly.

Is there a workaround for such a scenario? I could extend the webapplication with Windows authentication only, but I'd prefer to not have this overhead.

Looking forward to your feedback.

**Comment by Yvand** [comment]
@nicolas6969 thank you for your feedback.

Regarding your problem, it is probably not related to SPBypassLoginPage, and I expect you will have the exact same problem if you deactivate it and keep 2 (or more) authentication modes on the zone.

To fix it, you need to update your app to add HTTP header `X-FORMS_BASED_AUTH_ACCEPTED` with value `f` to the requests sent to SharePoint.
[Source](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/hh124553(v=office.14))

**Comment by nicolas6969** [comment]
Dear @Yvand 
Many thanks for the quick reply, very appreciated. Unfortunately I cannot implement your suggestion, as the requesting app is the on-premises data gateway we use for the Power Automate integration. Seems like a limitation given by the gateway application in this case.

**Comment by Yvand** [comment]
@nicolas6969 indeed, the gateway application does not allow you do configure this.
In such case, your only option is to extend the web application on a new zone that uses Windows only.

**Comment by nicolas6969** [comment]
Indeed. Again, thanks a lot @Yvand.
